wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 6
      - 8
      2:
      - 5
      - 6
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.39746468993299755
max_depth:
  desc: null
  value: 54
min_child_weight:
  desc: null
  value: 0.09122962220262201
n_estimators:
  desc: null
  value: 3631
num_leaves:
  desc: null
  value: 109
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.3947453561885113
reg_lambda:
  desc: null
  value: 1.3095421953315625
subsample:
  desc: null
  value: 0.7059875017073023
