wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.7726449666386831
max_depth:
  desc: null
  value: 51
min_child_weight:
  desc: null
  value: 0.0751388931282074
n_estimators:
  desc: null
  value: 2800
num_leaves:
  desc: null
  value: 6
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.1216259241735473
reg_lambda:
  desc: null
  value: 1.3071926774404976
subsample:
  desc: null
  value: 0.9031589898708888
