wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/src/pyprocessta/model/hyperparam_sweep.py
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1642143379
    t:
      1:
      - 1
      - 5
      - 8
      2:
      - 1
      - 5
      - 8
      3:
      - 2
      4: 3.8.11
      5: 0.12.9
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.4236094137444425
input_chunk_length:
  desc: null
  value: 31
kernel_size:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.15965734576507826
n_epochs:
  desc: null
  value: 200
num_filters:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 2
num_outputs:
  desc: null
  value: 0
weight_norm:
  desc: null
  value: true
