wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.4687827778025341
max_depth:
  desc: null
  value: 9
min_child_weight:
  desc: null
  value: 0.08093995334508991
n_estimators:
  desc: null
  value: 1304
num_leaves:
  desc: null
  value: 147
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.1353529208387572
reg_lambda:
  desc: null
  value: 1.3859804232877446
subsample:
  desc: null
  value: 0.5956050727653492
