wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/src/pyprocessta/model/hyperparam_sweep.py
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1641959798
    t:
      1:
      - 1
      - 5
      - 8
      2:
      - 1
      - 5
      - 8
      3:
      - 2
      4: 3.8.11
      5: 0.12.9
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.7956974249064167
input_chunk_length:
  desc: null
  value: 60
kernel_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.044591943155790334
n_epochs:
  desc: null
  value: 400
num_filters:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 8
num_outputs:
  desc: null
  value: 0
weight_norm:
  desc: null
  value: false
