wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.11153828796360472
input_chunk_length:
  value: 160
kernel_size:
  value: 5
lr:
  value: 0.010918527747726604
n_epochs:
  value: 100
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
