wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2230033017376143
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.19701408257975492
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
