wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.1432286642150479
input_chunk_length:
  value: 80
kernel_size:
  value: 5
lr:
  value: 0.24083038288801764
n_epochs:
  value: 100
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
