wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.1745041702864253
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.2733019319185293
n_epochs:
  value: 100
num_filters:
  value: 16
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
