wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.8508851661901352
input_chunk_length:
  value: 160
kernel_size:
  value: 3
lr:
  value: 0.026765005295877563
n_epochs:
  value: 200
num_filters:
  value: 16
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
