wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.8407593983457411
input_chunk_length:
  value: 60
kernel_size:
  value: 4
lr:
  value: 0.07072447873365521
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
