wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7940764512774411
input_chunk_length:
  value: 160
kernel_size:
  value: 3
lr:
  value: 0.1481794291734216
n_epochs:
  value: 100
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
