wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6270488523627261
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.07760487422928843
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
