wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.37773933137213056
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.3194665501981807
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: false
