wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5627375532912747
input_chunk_length:
  value: 60
kernel_size:
  value: 4
lr:
  value: 0.023819399528204964
n_epochs:
  value: 200
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
