wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.10072459504955848
input_chunk_length:
  value: 80
kernel_size:
  value: 5
lr:
  value: 0.0591967321889287
n_epochs:
  value: 200
num_filters:
  value: 64
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
