wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.6714932102788487
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.017537161972032568
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
