wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6650626389679231
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.010805714518950816
n_epochs:
  value: 100
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
