wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.8379103530627542
input_chunk_length:
  value: 160
kernel_size:
  value: 4
lr:
  value: 0.04745180224381652
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: true
