wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3227548031366928
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.03646739393945816
n_epochs:
  value: 100
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
