wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.23021065532348425
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.013633381045826305
n_epochs:
  value: 200
num_filters:
  value: 64
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: true
