wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7956974249064167
input_chunk_length:
  value: 60
kernel_size:
  value: 2
lr:
  value: 0.044591943155790334
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
