wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6681164022823272
input_chunk_length:
  value: 60
kernel_size:
  value: 3
lr:
  value: 0.104792130933993
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
