wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3308602908254289
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.015254246234181406
n_epochs:
  value: 300
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
