wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.24938945742945728
input_chunk_length:
  value: 60
kernel_size:
  value: 4
lr:
  value: 0.1431345005048098
n_epochs:
  value: 400
num_filters:
  value: 32
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
