wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7479988016842881
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.04631879413568329
n_epochs:
  value: 200
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
