wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4236094137444425
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.15965734576507826
n_epochs:
  value: 200
num_filters:
  value: 32
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
