wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2677822576967127
input_chunk_length:
  value: 31
kernel_size:
  value: 5
lr:
  value: 0.013331824732486251
n_epochs:
  value: 300
num_filters:
  value: 8
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
