wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5340293180557669
input_chunk_length:
  value: 160
kernel_size:
  value: 2
lr:
  value: 0.06140168779571299
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
