wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.06347775003272507
max_depth:
  desc: null
  value: 95
min_child_weight:
  desc: null
  value: 0.07065953370579471
n_estimators:
  desc: null
  value: 928
num_leaves:
  desc: null
  value: 174
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.2112072048875338
reg_lambda:
  desc: null
  value: 1.0802090452270883
subsample:
  desc: null
  value: 0.6470768375730793
