wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.342935147783804
max_depth:
  desc: null
  value: 90
min_child_weight:
  desc: null
  value: 0.08032195042819922
n_estimators:
  desc: null
  value: 1054
num_leaves:
  desc: null
  value: 6
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.4838794128461334
reg_lambda:
  desc: null
  value: 1.0069832947350168
subsample:
  desc: null
  value: 0.7312226394787253
