wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.7098504122507062
max_depth:
  desc: null
  value: 75
min_child_weight:
  desc: null
  value: 0.02649150587849249
n_estimators:
  desc: null
  value: 302
num_leaves:
  desc: null
  value: 288
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.4021972573817907
reg_lambda:
  desc: null
  value: 1.0758621192084172
subsample:
  desc: null
  value: 0.5153579338065929
