wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.18106539441638836
max_depth:
  desc: null
  value: 98
min_child_weight:
  desc: null
  value: 0.043839738504466326
n_estimators:
  desc: null
  value: 403
num_leaves:
  desc: null
  value: 289
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.0684454756804114
reg_lambda:
  desc: null
  value: 1.0080608871475127
subsample:
  desc: null
  value: 0.8181266836234591
