wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 2
      4: 3.8.8
      5: 0.10.26
      8:
      - 1
      - 5
