wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.8733744975946854
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 0.07007712361617514
n_estimators:
  desc: null
  value: 1957
num_leaves:
  desc: null
  value: 68
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.060459282919535
reg_lambda:
  desc: null
  value: 1.0616651654503813
subsample:
  desc: null
  value: 0.953073006212887
