wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.6198708691155584
max_depth:
  desc: null
  value: 37
min_child_weight:
  desc: null
  value: 0.006165662702824816
n_estimators:
  desc: null
  value: 319
num_leaves:
  desc: null
  value: 86
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.4638009139775299
reg_lambda:
  desc: null
  value: 1.096198971307183
subsample:
  desc: null
  value: 0.9746783412122594
