wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/src/pyprocessta/model/hyperparam_sweep.py
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1642017670
    t:
      1:
      - 1
      - 5
      - 8
      2:
      - 1
      - 5
      - 8
      3:
      - 2
      4: 3.8.11
      5: 0.12.9
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.8379103530627542
input_chunk_length:
  desc: null
  value: 160
kernel_size:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.04745180224381652
n_epochs:
  desc: null
  value: 400
num_filters:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 2
num_outputs:
  desc: null
  value: 1
weight_norm:
  desc: null
  value: true
