wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.7994076785939659
max_depth:
  desc: null
  value: 18
min_child_weight:
  desc: null
  value: 0.04676461193684842
n_estimators:
  desc: null
  value: 781
num_leaves:
  desc: null
  value: 76
reg_alpha:
  desc: null
  value: 1.2434376009490868
reg_lambda:
  desc: null
  value: 1.4408192491598304
subsample:
  desc: null
  value: 0.4412183697823636
