wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.47124556746627727
max_depth:
  desc: null
  value: 8
min_child_weight:
  desc: null
  value: 0.09659296495227815
n_estimators:
  desc: null
  value: 2970
num_leaves:
  desc: null
  value: 118
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.2890214300236102
reg_lambda:
  desc: null
  value: 1.3391381916235157
subsample:
  desc: null
  value: 0.5025100372518023
