wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.7536034595228153
max_depth:
  desc: null
  value: 42
min_child_weight:
  desc: null
  value: 0.07918097170183468
n_estimators:
  desc: null
  value: 3797
num_leaves:
  desc: null
  value: 309
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.2193634180581938
reg_lambda:
  desc: null
  value: 1.017808069136718
subsample:
  desc: null
  value: 0.4031076149048597
