wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.3589040148228566
max_depth:
  desc: null
  value: 13
min_child_weight:
  desc: null
  value: 0.09338820787862688
n_estimators:
  desc: null
  value: 1349
num_leaves:
  desc: null
  value: 75
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.467279004775178
reg_lambda:
  desc: null
  value: 1.2325812042074835
subsample:
  desc: null
  value: 0.5148624108732519
