wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.3772042832262256
max_depth:
  desc: null
  value: 39
min_child_weight:
  desc: null
  value: 0.013263320638317987
n_estimators:
  desc: null
  value: 228
num_leaves:
  desc: null
  value: 440
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.455966914745086
reg_lambda:
  desc: null
  value: 1.4146472357128888
subsample:
  desc: null
  value: 0.4800574667650975
