wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 8
      2:
      - 5
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.4626822591148545
max_depth:
  desc: null
  value: 30
min_child_weight:
  desc: null
  value: 0.004337690407076374
n_estimators:
  desc: null
  value: 1096
num_leaves:
  desc: null
  value: 311
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.4136138431251049
reg_lambda:
  desc: null
  value: 1.4730662888112172
subsample:
  desc: null
  value: 0.565371117630658
