wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    t:
      1:
      - 5
      - 6
      - 8
      2:
      - 5
      - 6
      - 8
      3:
      - 2
      4: 3.8.8
      5: 0.10.28
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.02726451348709738
max_depth:
  desc: null
  value: 63
min_child_weight:
  desc: null
  value: 0.0033791823104625325
n_estimators:
  desc: null
  value: 671
num_leaves:
  desc: null
  value: 496
objective:
  desc: null
  value: huber
reg_alpha:
  desc: null
  value: 1.2154447628656724
reg_lambda:
  desc: null
  value: 1.3625719261724307
subsample:
  desc: null
  value: 0.9724916482256001
